require("modules.nvim-tree")
require("modules.treesitter")
require("modules.telescope")
require("modules.lualine")
require("modules.colorizer")
require("modules.autopairs")
-- require("modules.bufferline")
require("modules.toggleterm")
require("modules.zenmode")
require("modules.transparent")
