local Palette = require "decay.palettes.palette"

-- background shades and bright colors
-- are being autogenerated by `Palette`.
return Palette:from_dict {
  key = "default",
  colors = {
    -- base palette
    background = '#171a1f',
    foreground = '#b6beca',
    red = '#fc7b81',
    green = '#94f7c5',
    yellow = '#ffeba6',
    blue = '#8cc1ff',
    purple = '#e2a6ff', -- TODO (fallback -> magenta)
    magenta = '#e2a6ff',
    cyan = '#90daff',
    aqua = '#90daff', -- TODO (fallback -> cyan)
    orange = '#ffeba6', -- TODO (fallback -> yellow)
    white = '#fafdff',
    accent = '#94f7c5',

    -- colors generators
    _generate = {
      git = function (self)
        return {
          add = self.colors.green,
          change = self.colors.yellow,
          delete = self.colors.red
        }
      end,
      git_signs = function (self)
        return {
          add = self.colors.green,
          change = self.colors.yellow,
          delete = self.colors.red
        }
      end,
      diff = function (self)
        return {
          add = self.colors.green,
          change = self.colors.yellow,
          delete = self.colors.red
        }
      end
    },
  }
}
