local Palette = require "decay.palettes.palette"

-- background shades and bright colors
-- are being autogenerated by `Palette`.
return Palette:from_dict {
  key = "default",
  colors = {
    -- base palette
    background = '#131010',
    foreground = '#c2c2d6',
    red = '#be6875',
    green = '#93bb7b',
    yellow = '#cfbf85',
    blue = '#8499e0',
    accent = '#8499e0',
    purple = '#7b71bf',
    magenta = '#a984e0',
    cyan = '#8abae3',
    aqua = '#8abae3', -- TODO (fallback -> cyan)
    orange = '#cfa085',
    white = '#b5b5cd',

    -- colors generators
    _generate = {
      git = function (self)
        return {
          add = self.colors.green,
          change = self.colors.yellow,
          delete = self.colors.red
        }
      end,
      git_signs = function (self)
        return {
          add = self.colors.add,
          change = self.colors.yellow,
          delete = self.colors.red
        }
      end,
      diff = function (self)
        return {
          add = self.colors.green,
          change = self.colors.yellow,
          delete = self.colors.red
        }
      end
    },
  }
}
